name: Sync Cypwn Repo (Full Mirror)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # tiap 6 jam

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Cypwn JSON
        run: |
          curl -L https://ipa.cypwn.xyz/cypwn.json -o raw.json

          jq '
            if .apps then {apps:.apps}
            elif .repoApps then {apps:.repoApps}
            else .
            end
          ' raw.json > cypwn.json

          rm raw.json

      - name: Commit changes
        run: |
          git config user.name "AppleJr Bot"
          git config user.email "bot@applejr.net"
          git add cypwn.json
          git commit -m "🔄 Auto sync Cypwn repo" || echo "No changes"
          git push
